version: "3.8"
services:
  db:
    container_name: Postgres_py
    image: postgres:16.0
    environment:
      POSTGRES_DB: ${PSQL_DB}
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASS}
    ports:
      - "5432:5432"
    networks:
      - postgres-net
    volumes:
      - postgres-py:/var/lib/postgresql/data
volumes:
  postgres-py:
networks:
  postgres-net:
    driver: bridge
